In [1]:
import sys
import numpy as np

In [2]:
sys.getsizeof([1])


64

In [3]:
np.array([1]).nbytes

4

In [4]:
np.random.random(size=2)#浮点数都是从0-1中随机

array([0.14396079, 0.49296223])

In [5]:
np.random.normal(size=2)

array([-0.95421176, -0.30558396])

In [6]:
np.random.rand(2, 4)#生成指定维度的服从均匀分布的随机数，输入参数为维度

array([[0.30542497, 0.47796051, 0.44919535, 0.61588489],
       [0.28050527, 0.03404372, 0.39353689, 0.87168319]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [9]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [10]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
np.linspace(0, 1, 20, False)#等间隔取

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3, 3), dtype=np.int)

C:\Users\may_wu\AppData\Local\Temp/ipykernel_22736/383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [27]:
"Hello World"[6]

'W'

In [29]:
import numpy as np# Import the numpy package under the name np

In [30]:
print(np.__version__)# Print the numpy version and the configuration

1.20.3


In [31]:
np.zeros(10)# Create a numpy array of size 10, filled with zeros.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.arange(10,50)#Create a numpy array with values ranging from 10 to 49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [40]:
np.ones([2,2],dtype=np.float)#Create a numpy matrix of 2*2 integers, filled with ones.

C:\Users\may_wu\AppData\Local\Temp/ipykernel_22736/287650130.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2],dtype=np.float)#Create a numpy matrix of 2*2 integers, filled with ones.


array([[1., 1.],
       [1., 1.]])

In [43]:
X = np.arange(4,dtype=int)

In [44]:
np.ones_like(X)

array([1, 1, 1, 1])

In [46]:
X = np.array([[1,2,3],[4,5,6]],dtype=int)

In [47]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
np.zeros([4,4],dtype=int)+5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.random.randint(10,size=3)

array([3, 4, 8])

In [55]:
np.random.randn(3,3,3)

array([[[-1.25504163,  0.27793497,  0.80543738],
        [ 2.13380468, -2.39545613, -1.98648586],
        [ 0.2182981 , -0.32369315,  0.3120951 ]],

       [[ 0.38143165, -0.30612507,  0.30322362],
        [ 1.22053215,  0.22048321, -0.77417958],
        [ 0.33281708, -0.86394134, -0.34807708]],

       [[ 1.56517766, -1.2556923 , -0.85198288],
        [ 0.0759488 ,  0.12734492, -0.48176109],
        [-1.65608605,  0.1249234 , -0.52493127]]])

In [56]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [57]:
Y = np.array(X)
print(Y, type(Y)) # different type

[1 2 3] <class 'numpy.ndarray'>


In [59]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))


[5 2 3] 2147210517744


In [60]:
Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 2147210581552


In [61]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [65]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))
print(Z.size * Z.itemsize)

800 bytes
800


In [63]:
Z.size

100

In [64]:
Z.itemsize

8

In [66]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [67]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [68]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [69]:
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [70]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [71]:
X[-2:, -2:]

array([[11, 12],
       [15, 16]])

In [72]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [73]:
X[-1] = 1

In [74]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [75]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [76]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

In [77]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False